### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jfilter** [thisisparker/track-the-news#1] opened 2018-06-21 08:46 UTC
Hey Parker,

I tried to deploy track-the-news but run into a seg fault as soon it found an article. Can you image where this is coming from?

```
Running with configuration files in /home/jfilter/code/ifg-feed/ttnconfig
No blocklist to load.
Matching against the following words: ['Informationsfreiheitsgesetz', 'Tranzparenzgesetz', 'Informationszugangsgesetz', 'Landestransparenzgesetz', 'Verbraucherinformationsgesetz', 'Umweltinformationsgesetz']
Checking Netzpolitik.org article 1/25
Got one!
Segmentation fault
```

Part of the config is here: https://github.com/jfilter/ifg-feed/tree/master/ttnconfig

**Comment by jfilter** [comment] 2018-06-21 09:54
It's most likely related to https://github.com/python-pillow/Pillow/issues/2826 and only occurs with Python3. I will make your script run with Python2.

It breaks here: https://github.com/thisisparker/track-the-news/blob/master/trackthenews/core.py#L131

**Comment by thisisparker** [comment] 2018-06-21 20:43
Thank you so much! That's a curious bug and one I can't reproduce, but I've merged in your PR and it looks like a good solution (at least for now!).

**Closed by thisisparker** 2018-06-21 20:43 UTC
